site_name: Kozmoz
site_dir: docs_build
use_directory_urls: false

pages:
    - Home: index.md
    - Api:
      - v1: api/v1.md
    - Backend:
      - Celery: backend/celery.md
      - Development: backend/development.md
