# Generated by Django 2.2.2 on 2019-06-07 13:00

from django.db import migrations, models
import django.db.models.deletion
import posts.formatChecker


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Comment')),
                ('comment_published_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Published Date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('comment_published_date',),
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Sad'), (2, 'Funny'), (3, 'Angry')])),
                ('voting_date', models.DateTimeField(auto_now_add=True, verbose_name='Voting Date')),
            ],
            options={
                'verbose_name': 'Comments Vote',
                'verbose_name_plural': 'Comments Votes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('media', posts.formatChecker.ContentTypeRestrictedFileField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Sad'), (2, 'Funny'), (3, 'Angry')])),
                ('voting_date', models.DateTimeField(auto_now_add=True, verbose_name='Voting Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Posts Vote',
                'verbose_name_plural': 'Posts Votes',
            },
        ),
    ]
