# Generated by Django 2.0.6 on 2018-06-26 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.formatChecker


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('publishing_date', models.DateTimeField(verbose_name='Date')),
                ('media', posts.formatChecker.ContentTypeRestrictedFileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('user',),
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
