# Generated by Django 2.0.6 on 2018-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180710_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
