# Generated by Django 2.0.6 on 2018-07-16 11:41

from django.db import migrations, models
import django.db.models.deletion
import posts.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Sad'), (2, 'Funny'), (3, 'Angry')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='posts.Comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=posts.formatChecker.ContentTypeRestrictedFileField(upload_to='media'),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.Post', verbose_name='Post'),
        ),
    ]
