# Generated by Django 2.0.6 on 2018-07-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180716_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Sad'), (2, 'Funny'), (3, 'Angry')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='posts.Comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Comment Vote',
                'verbose_name_plural': 'Comment Votes',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Like'), (1, 'Sad'), (2, 'Funny'), (3, 'Angry')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Vote',
                'verbose_name_plural': 'Post Votes',
            },
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
