# Generated by Django 2.0.6 on 2018-07-16 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180716_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentvote',
            options={'verbose_name': 'Comments Vote', 'verbose_name_plural': 'Comments Votes'},
        ),
        migrations.AlterModelOptions(
            name='postvote',
            options={'verbose_name': 'Posts Vote', 'verbose_name_plural': 'Posts Votes'},
        ),
        migrations.AddField(
            model_name='commentvote',
            name='voting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Voting Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvote',
            name='voting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Voting Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment Published Date'),
        ),
    ]
